#!/usr/bin/expect

set route_name "mscjoeri"
set rule [lindex $argv 0]
#set rule {{destination 1.1.1.1/32} {source 218.216.183.36/32} {protocol udp} {source-port 53}}

spawn ssh joeri-msc-student@145.145.18.94
expect "Enter passphrase*"
send "joeri\r"
expect ">"
send "configure\r"
send "edit routing-options flow route $route_name\r"

foreach type $rule {
	send "set match $type\r"
}
send "set then discard\r"
send "commit\r"
send "exit\r"
send "exit\r"
send "exit\r"
interact
