#!/usr/bin/expect

set route_name "mscjoeri"
#set rule {{destination 1.1.1.1/32} {source 218.216.183.36/32} {protocol udp} {source-port 53}}

set filename [lindex $argv 0]
set f [open $filename]
set rules [split [read $f] "\n"]
close $f

spawn ssh joeri-msc-student@145.145.18.94
expect "Enter passphrase*"
send "joeri\r"
expect ">"
send "configure\r"

# From here, loop through all lines in $rules
set counter 1
foreach rule $rules {
	#puts stdout $rules
	append route_name counter
	send "edit routing-options flow route $route_name\r"
	foreach type $rule {
		send "set match $type\r"
	}
	incr counter
}

send "set then discard\r"
send "commit\r"
send "exit\r"
send "exit\r"
send "exit\r"
interact
